name: Run Smoke Deployment
description: Launches an archi deployment and runs smoke tests.

inputs:
  deployment-name:
    description: Name used for the temporary deployment.
    required: true
  config-path:
    description: Source path to the deployment config file.
    required: true
    default: tests/pr_preview_config/pr_preview_config.yaml
  config-destination:
    description: Destination path where the config will be copied.
    required: false
    default: configs/ci/ci_config.generated.yaml
  extra-env:
    description: Additional environment variables (key=value lines)
    required: false
    default: ""
  services:
    description: Services list passed to archi create.
    required: false
    default: chatbot
  hostmode:
    description: Whether to include --hostmode when creating the deployment.
    required: false
    default: "true"
  wait-url:
    description: Health endpoint to poll for readiness.
    required: false
    default: http://localhost:2786/api/health
  wait-attempts:
    description: Number of readiness checks before failing.
    required: false
    default: "60"
  wait-sleep-seconds:
    description: Seconds to sleep between readiness attempts.
    required: false
    default: "2"
  base-url:
    description: Base URL passed to smoke.sh via BASE_URL.
    required: false
    default: http://localhost:2786
  use-podman:
    description: Use podman instead of docker.
    required: false
    default: "false"

outputs:
  deployment-name:
    description: The deployment name used for the smoke test.
    value: ${{ inputs.deployment-name }}

runs:
  using: composite
  steps:
    - name: Ensure smoke scripts are executable
      shell: bash
      run: |
        set -euo pipefail
        chmod +x tests/smoke/*.sh scripts/dev/run_smoke_preview.sh
    - name: Install archi from workspace (sync templates)
      shell: bash
      run: |
        set -euo pipefail
        pip install -e .
    - name: Prepare podman runtime dir
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p /var/lib/a2rchi/run
        chmod 700 /var/lib/a2rchi/run
    - name: Configure podman storage (runroot/graphroot)
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p /var/lib/a2rchi/run/containers
        chmod 700 /var/lib/a2rchi/run/containers
        mkdir -p /var/lib/a2rchi/.config/containers
        mkdir -p /var/lib/a2rchi/.local/share/containers/storage

    - name: Run shared smoke runner
      shell: bash
      env:
        DEPLOYMENT_NAME: ${{ inputs.deployment-name }}
        CONFIG_SRC: ${{ inputs.config-path }}
        CONFIG_DEST: ${{ inputs.config-destination }}
        EXTRA_ENV: ${{ inputs.extra-env }}
        SERVICES: ${{ inputs.services }}
        HOSTMODE: ${{ inputs.hostmode }}
        WAIT_URL: ${{ inputs.wait-url }}
        WAIT_ATTEMPTS: ${{ inputs.wait-attempts }}
        WAIT_SLEEP: ${{ inputs.wait-sleep-seconds }}
        BASE_URL: ${{ inputs.base-url }}
        USE_PODMAN: ${{ inputs.use-podman }}
        HOME: /var/lib/a2rchi
        XDG_RUNTIME_DIR: /var/lib/a2rchi/run
        CONTAINERS_STORAGE_CONF: /var/lib/a2rchi/.config/containers/storage.conf
        PODMAN_TMPDIR: /var/lib/a2rchi/run/tmp
      run: |
        set -euo pipefail
        mkdir -p /var/lib/a2rchi/run/tmp
        ./scripts/dev/run_smoke_preview.sh "${DEPLOYMENT_NAME}"
