# bare minimum configuration needed for a2rchi
name: bare_minimum_configuration #REQUIRED

global:
  TRAINED_ON: "SubMIT and the people who started A2rchi" #REQUIRED

locations_of_secrets:
  - ~/.secrets/my_secrets # in this dir, there should be, e.g., pg_password.txt

chains:
  chain:
    MODEL_NAME: OpenAIGPT4
    CONDENSE_MODEL_NAME: OpenAIGPT4
  prompts:
    CONDENSING_PROMPT: configs/prompts/condense.prompt #REQUIRED
    MAIN_PROMPT: configs/prompts/submit.prompt #REQUIRED
