name: grading_test

global:
  TRAINED_ON: "rubrics, class info, etc."

locations_of_secrets:
  - /home/submit/lavezzo/a2rchi/A2rchi/secrets/
  - /home/submit/lavezzo/a2rchi/A2rchi/secrets/grader/

data_manager:
  input_lists:
    - configs/miscellanea.list
  chromadb_port: 8000
  chromadb_external_port: 8001
  embedding_name: HuggingFaceEmbeddings

a2rchi:
  pipeline: GradingPipeline
  pipeline_map:
    GradingPipeline:
      prompts:
        required:
          grading_final_grade_prompt: configs/prompts/submit.prompt  
      models:
        required:
          grading_final_grade_model: HuggingFaceOpenLLM
    ImageProcessingPipeline:
      prompts:
        required:
          image_processing_prompt: configs/prompts/image_processing.prompt
      models:
        required:
          image_processing_model: HuggingFaceOpenLLM

interfaces:
  grader_app:
    num_problems: 1
    local_rubric_dir: /home/submit/lavezzo/a2rchi/grading/my_rubrics
    local_users_csv_dir: /home/submit/lavezzo/a2rchi/grading/logins
