name: prod_submit

global:
  TRAINED_ON: "the SubMIT Cluster"  

locations_of_secrets:
  - /home/submit/lavezzo/a2rchi/A2rchi/secrets/

data_manager:
  input_lists:  
    - configs/submit.list
    - configs/miscellanea.list
  chromadb_port: 8000
  chromadb_external_port: 8001
  embedding_name: HuggingFaceEmbeddings

a2rchi:
  pipeline: QAPipeline
  pipeline_map:
    QAPipeline:
      prompts:
        required:
          condense_prompt: configs/prompts/condense.prompt  
          chat_prompt: configs/prompts/submit.prompt  
      models:
        required:
          chat_model: HuggingFaceOpenLLM
          condense_model: HuggingFaceOpenLLM


interfaces:
  chat_app:
    HOSTNAME: "submit75.mit.edu" 
