name: prod_submit

global:
  TRAINED_ON: "the SubMIT Cluster"  

locations_of_secrets:
  - /home/submit/lavezzo/a2rchi/A2rchi/secrets/
  - ~/.secrets/api_tokens
  - ~/.secrets/salts_and_internal_passwords
  - ~/.secrets/submit_cleo_and_mailer_passwords

data_manager:
  input_lists:  
      - configs/submit.list
      - configs/miscellanea.list

a2rchi:
  pipeline_map:
    QAPipeline:
      prompts:
        condense_prompt: configs/prompts/condense.prompt  
        qa_prompt: configs/prompts/submit.prompt  
      models:
        qa_model: DumbLLM
        condense_model: DumbLLM

utils:
  embeddings:
    EMBEDDING_NAME: HuggingFaceEmbeddings

interfaces:
  chat_app:
    HOSTNAME: "submit75.mit.edu" 
