name: wisdqm
global:
  TRAINED_ON: "WisDQM Scrapes"
 
chains:
  input_lists:  
    - configs/wisdqm.list
  chain:
    MODEL_NAME: HuggingFaceOpenLLM
    CONDENSE_MODEL_NAME: HuggingFaceOpenLLM
    SUMMARY_MODEL_NAME: HuggingFaceOpenLLM
    MODEL_CLASS_MAP:
      HuggingFaceOpenLLM:
        kwargs:
          base_model: "Qwen/Qwen2.5-7B-Instruct-1M"
          quantization: True
  prompts:
    CONDENSING_PROMPT: configs/prompts/condense.prompt  
    MAIN_PROMPT: configs/prompts/wisdqm.prompt  
    SUMMARY_PROMPT: configs/prompts/summary.prompt  

interfaces:
  uploader_app:
    PORT: 5005
    EXTERNAL_PORT: 5005
    verify_urls: False
  chat_app:
    PORT: 7865
    EXTERNAL_PORT: 7865
    HOSTNAME: "submit76.mit.edu" 
  grafana:
    EXTERNAL_PORT: 3005

locations_of_secrets:
  - ~/.a2rchi/base

utils:
  data_manager:
    chromadb_external_port: 8005
  embeddings:
    EMBEDDING_NAME: HuggingFaceEmbeddings
    EMBEDDING_CLASS_MAP:
      HuggingFaceEmbeddings:
        similarity_score_reference: 10
  sso:
    ENABLED: True
    SSO_CLASS: CERNSSOScraper
    SSO_CLASS_MAP:
      CERNSSOScraper:
        kwargs:
          headless: True  # headless mode for scraping, as it is run in a container
          max_depth: 2    # max depth for crawling from starting URL
